version: '3.9'

services:
  backend:
    build: .
    container_name: backend_app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/midb
      - JWT_SECRET=supersecreto
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
