version: '3.8'

services:
  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongo_data:/data/db
    restart: always

  backend:
    build: .
    container_name: backend
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always

volumes:
  mongo_data:
