version: '3.9'

services:
  backend:
    build: .
    container_name: backend_app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/midb
      - JWT_SECRET=supersecreto
    depends_on:
      - mongo

 
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"  # expone el puerto para acceso externo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: supersecreto
    volumes:
      - ./data:/data/db

volumes:
  mongo_data:
